language: cpp
compiler: gcc
before_install:
    - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo apt-get update -q -y
    - sudo apt-get install -q -y libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev doxygen graphviz
script: ./cmake_gcc.sh -DURHO3D_LIB_TYPE=$TEST_LIB_TYPE -DENABLE_64BIT=1 -DENABLE_LUAJIT=1 -DENABLE_LUAJIT_AMALG=1 -DENABLE_SAMPLES=1 -DENABLE_TOOLS=1 -DENABLE_EXTRAS=1 && cd Build && make
after_success: rake travis
env:
  global:
    - secure: ST80PPq8cTIZ5WRgX4BJ7gKhHonNge9GdYH0PuTvCZot13Rk+oNkbzkkCT/KuQHmyUU65gE2HCyMYYqNDNyxy0Upi8jMUjgXdy7SN5zORVhyc/Ymfd6rt3sgVOT6YYlbegI3sFLVdaH4jdyyMqPQHW72StZ25NUQi0p682FAGD0=
    - secure: Ry36SYyKJ0WNuAd83q5vCUwU6Mm6I9DDWrJmo5DQmdh2rgiLggUBsWklo5eYVa1i6YkuDzaNIe/TKpCWrCJrdtwBVZ/ze8x859QoRp1yA9/GH/Ua9eWm7KmtG98W9fwbe3aLsdY329pTCvTuWBCWn6vbM/2zahwwHua1bGn4nyw=
  matrix:
    - TEST_LIB_TYPE=STATIC
    - TEST_LIB_TYPE=SHARED
