language: cpp
compiler: gcc
before_install:
    - sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - sudo apt-get update -q -y
    - sudo apt-get install -q -y --no-install-recommends libasound2-dev doxygen graphviz
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24
script: ./cmake_gcc.sh -DURHO3D_LIB_TYPE=$TEST_LIB_TYPE -DENABLE_64BIT=1 -DENABLE_LUAJIT=1 -DENABLE_LUAJIT_AMALG=1 -DENABLE_SAMPLES=1 -DENABLE_TOOLS=1 -DENABLE_EXTRAS=1 -DENABLE_TESTING=1 && cd Build && make && make test
after_success: rake travis
env:
  global:
    secure: DE9IUM+pIV757GU0ccfDJhA752442pKu3DyBthrzHW9+GbsqbfuJOx045CYNN5vOWutFPC0A51B9WxhLNpXXqD3mfU8MhP1gkF7SskrHvcAPrCyfdqZf1Q8XDP5phm2KbHhhwxQMYmmicd6yj8DPNy2wRoSgPSDp/ZUDk51XZDU=
  matrix:
    - TEST_LIB_TYPE=STATIC
    - TEST_LIB_TYPE=SHARED
